version: "3"
services:
  linqua-server:
    image: linqua:latest
    network_mode: "host"
    restart: on-failure

  linqua-db:
    image: docker.io/library/mongo:latest
    expose:
      - "8080"
    volumes:
      - /srv/mongo-data:/data/db:Z
    restart: on-failure