class LinquaExceptions:
    class UserUnknown(Exception):
        ...
    class UserAlreadyExists(Exception):
        ...
    class TaskUnknown(Exception):
        ...
    class WrongTaskClass(Exception):
        ...

