from typing import *
from task import Task, ObjectId
from speech import Speech, WordPresent, GrammarError
from pydantic import BaseModel
from words import Words
from datetime import datetime


class HitwordsUsed(BaseModel):
    word: str
    used: bool

class TaskTalkScore(BaseModel):
    length: int
    hitwods: int

class TaskTalkReport(BaseModel):
    text_recognized: str
    words_recognized: List[str]
    hitwords_used: List[WordPresent]
    grammar_errors: List[GrammarError]
    score: TaskTalkScore

class TalkAutoTaskInfo(BaseModel):
    taskid: str
    tmpid: str
    text: str
    hitwords: List[str]
    time_limit: int
    countdown: int
    word_count_min: int
    word_count_max: int
    word_count_best: int

    b64image: Optional[str] = None

class TalkAutoTask(Task):
    TASK_TYPE = 'TALK-AUTOGEN'

    def __init__(self, id: str) -> None:
        super().__init__(id)
        self.text = self._task_data['text']
        self.hitwords = self._task_data['hitwords']
        self.word_count_min = self._task_data['word_count_min']
        self.word_count_max = self._task_data['word_count_max']
        self.word_count_best = self._task_data['word_count_best']
        self.time_limit = self._task_data['time_limit']
        self.countdown = self._task_data['countdown']
        self.dynamic_hitwords = self._task_data['dynamic_hitwords']

    def solve(self, speech: Speech, tmpid: str):
        self.solution: Speech = speech
        if not (tmp_data := self.tmp_storage_pop(tmpid)):
            raise Exception('no tmp data for autogenerated task')
        self.hitwords = tmp_data['words']
        self.hitwords_used = self.solution.has_words(self.hitwords)
        
        return TaskTalkReport(
            text_recognized = self.solution.text,
            words_recognized = self.solution.words,
            hitwords_used = self.hitwords_used,
            grammar_errors = self.solution.grammar,
            score = self.score
        )

    def generate(self, min_freq: float = 0, max_freq: float = 1) -> TalkAutoTaskInfo:
        wordsDB = Words()
        for dyn_word in self.dynamic_hitwords:
            self.hitwords += wordsDB.get(word_type=dyn_word['class'], amount=dyn_word['count'], min_freq=min_freq, max_freq=max_freq)
        tmpid = self.tmp_storage_save(self.hitwords)
        return TalkAutoTaskInfo(
            taskid = self.id,
            tmpid = tmpid,
            text = self.text,
            hitwords = self.hitwords,
            time_limit = self.time_limit,
            countdown = self.countdown,
            word_count_min = self.word_count_min,
            word_count_max = self.word_count_max,
            word_count_best = self.word_count_best,
        )

    def tmp_storage_save(self, words: List[str]) -> str:
        data  = dict(
            words = words,
            task_type = self.TASK_TYPE,
            created = datetime.now().strftime(Task.TIME_FORMAT)
        )
        return str(Task.tmp_storage.insert_one(data).inserted_id)

    def tmp_storage_pop(self, tmpid: str):
        oid = ObjectId(tmpid)
        data = Task.tmp_storage.find_one({'_id': oid})
        Task.tmp_storage.delete_one({'_id': oid})
        return data

    @property
    def score(self) -> TaskTalkScore:
        #HITWORDS
        hits = 0
        for used_word in self.hitwords_used:
            hits += 1 if used_word.present else 0
        score_hitword = int(100 * hits / len(self.hitwords))
        score_length = int(100 if self.solution.word_count > self.word_count_min else 100 * (self.solution.word_count/self.word_count_min))
        return TaskTalkScore(
            length=score_length,
            hitwods=score_hitword
        )

    @staticmethod
    def create(creator: str, text: str, hitwords: List[str], word_count_min: int, word_count_max: int, word_count_best: int, time_limit: int, countdown: int, dynamic_hitwords: List[Dict], **kwargs):
        return super(TalkAutoTask, TalkAutoTask).create(
            creator = creator,
            task_type = TalkAutoTask.TASK_TYPE,
            task_attribs = dict(
                text = text,
                hitwords = hitwords,
                word_count_min = word_count_min,
                word_count_max = word_count_max,
                word_count_best = word_count_best,
                time_limit = time_limit,
                countdown = countdown,
                dynamic_hitwords = dynamic_hitwords
            )
        )